### PR TITLE
add flush interval control for primary file store

### PR DESCRIPTION
**Pull request by thekiki**
`fflush()` for specified file store periodically

### CODE REVIEW

**Comment by thekiki** [comment]
this is very helpful for traditional file-based log collector, without this new feature, sometime it's quite hard to get new log in time.

**Comment by thekiki** [comment]
hi, please review this change. without this feature, it's hard to convince our team members to deploy kids in our serving system. or you may have better ideas, feel free to propose.

thanks

**Comment by liyichao** [comment]
LGTM. It seems hard to test this.

One question about the use case, what do you mean by `traditional file-based log collector`. Do you collect log firstly via kids to kids server and save to file, then parse the file to send it otherwhere?

**Comment by thekiki** [comment]
1. it make easier to integrate with file-based or inotify-based process scripts.
2. (may be more important) when some QE/OP guys try reproducing issues and we try to collect error logs from kids, it would be annoying to wait for fwrite buffer to be filled.

**Comment by liyichao** [comment]
Please add some docs, https://github.com/zhihu/kids/blob/master/doc/store.md

**Comment by thekiki** [comment]
added, please review.

**Pull request merged**
